@echo off
echo Clearing npm cache...
call npm cache clean --force
cd frontend
echo Clearing frontend node_modules...
rmdir /s /q node_modules
echo Reinstalling...
call npm install
echo Building...
call npm run build
cd ..
pause
